listening-port=3478
listening-ip=0.0.0.0
tls-listening-port=5349
realm=turn.open-avatar-chat.turnserver
user=admin:admin
lt-cred-mech
min-port=49152
max-port=65535
cert=/etc/turn_cert.pem
pkey=/etc/turn_key.pem
allowed-peer-ip=0.0.0.0
